### ISSUE TITLE
Plugin doesnt work for me.

### ISSUE THREAD

**Issue by SillySoon** [Maticzpl/MoreHazards#2]
Idc why but the plugins doesnt work on my server, help me qwq
Here my Configs:
[stuff.txt](https://github.com/Maticzpl/MoreHazards/files/6292903/stuff.txt)

**Comment by Maticzpl** [comment]
> Idc why but the plugins doesnt work on my server, help me qwq
> Here my Configs:
> [stuff.txt](https://github.com/Maticzpl/MoreHazards/files/6292903/stuff.txt)
> 

Whats not working?

**Comment by SillySoon** [comment]
Somehow after a clean Restart the Tesla System for MTF's work.
Im now waiting for the random Elevator & Door Events

**Comment by SillySoon** [comment]
> Somehow after a clean Restart the Tesla System for MTF's work.
> Im now waiting for the random Elevator & Door Events

The Events "breakable_elevators" , "door_malfunction" and "door_system_breakdown" doesnt work for me for some reason. there all "enabled: true" but nothing happens

**Comment by Maticzpl** [comment]
Set the cooldowns to something low like 20 seconds
And chances to 100 just to test if they will ever happen

Also check if there is anything in the console

**Comment by SillySoon** [comment]
> Set the cooldowns to something low like 20 seconds
> And chances to 100 just to test if they will ever happen
> 
> Also check if there is anything in the console

It works now, i think the problem was that I did this:

```
breakable_elevators:
    - LczA
    - LczB
    - Gate A 
    #here is now GateA
    - Gate B 
    #here is now GateB
```

So far it works, next question would be for the cassie system.
Chance (0/100)
For what? for each letter?

**Comment by Maticzpl** [comment]
I mentioned chance per elevator
So for 50 you would expect roughly half of the elevators to break

The cassie messages have a chance of glitches and jams but im not sure how it works since exiled handles that internaly
I guess its per character in a sentence but im not sure

**Comment by SillySoon** [comment]
> I mentioned chance per elevator
> So for 50 you would expect roughly half of the elevators to break
> 
> The cassie messages have a chance of glitches and jams but im not sure how it works since exiled handles that internaly
> I guess its per character in a sentence but im not sure

Okay Thanks for Helping ! made my day (or night lol)
